import DashboardLayout from "@/components/DashboardLayout";
import { Badge } from "@/components/ui/badge";
import { Database, Info, ShieldCheck, UserRound } from "lucide-react";

const APP_ICON_URL = "/logo.svg";

export default function About() {
  return <DashboardLayout><div className="mx-auto w-full max-w-5xl space-y-6 pb-8">
    <section className="relative overflow-hidden rounded-[1.75rem] border border-white/10 bg-[#0d1426] px-6 py-8 shadow-[0_25px_80px_-45px_rgba(34,211,238,.5)] sm:px-8"><div className="pointer-events-none absolute -right-20 -top-24 h-72 w-72 rounded-full bg-cyan-400/15 blur-3xl" /><div className="relative flex flex-col gap-5 sm:flex-row sm:items-center"><div className="flex h-20 w-20 shrink-0 items-center justify-center rounded-2xl border border-white/15 bg-white/[.07] p-2"><img src={APP_ICON_URL} alt="Logo Pos Indonesia" className="h-full w-full object-contain" /></div><div><p className="flex items-center gap-2 text-[11px] font-semibold uppercase tracking-[.17em] text-white"><Info className="h-3.5 w-3.5" />Informasi aplikasi</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-white">Dashboard Monitoring Operasi Kurir</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-white">Aplikasi internal untuk memantau aktivitas kiriman dan operasional kurir secara langsung dari sumber data operasional.</p></div></div></section>
    <section className="grid gap-4 md:grid-cols-3"><article className="rounded-2xl border border-cyan-300/60 bg-cyan-50 p-5 !text-slate-950"><span className="inline-flex rounded-xl bg-cyan-200 p-2 !text-slate-950"><Info className="h-5 w-5" /></span><p className="mt-4 text-[11px] font-semibold uppercase tracking-[.13em] !text-slate-950">Versi aplikasi</p><p className="mt-2 text-xl font-semibold !text-slate-950">1.0.0</p><Badge className="app-badge-primary mt-3 border-0">Rilis operasional</Badge></article><article className="rounded-2xl border border-violet-300/60 bg-violet-50 p-5 !text-slate-950"><span className="inline-flex rounded-xl bg-violet-200 p-2 !text-slate-950"><UserRound className="h-5 w-5" /></span><p className="mt-4 text-[11px] font-semibold uppercase tracking-[.13em] !text-slate-950">Dibuat oleh</p><p className="mt-2 text-base font-semibold !text-slate-950">Barkah</p><p className="mt-1 text-sm !text-slate-950">KCU Jakarta Premer 1300</p><p className="mt-3 text-xs !text-slate-950">@Agust2026</p></article><article className="rounded-2xl border border-emerald-300/60 bg-emerald-50 p-5 !text-slate-950"><span className="inline-flex rounded-xl bg-emerald-200 p-2 !text-slate-950"><Database className="h-5 w-5" /></span><p className="mt-4 text-[11px] font-semibold uppercase tracking-[.13em] !text-slate-950">Sumber data</p><p className="mt-2 text-base font-semibold !text-slate-950">Kibana - ElasticSearch</p><p className="mt-3 text-xs leading-5 !text-slate-950">Data dibaca langsung dari indeks operasional.</p></article></section>
    <section className="rounded-2xl border border-white/10 bg-slate-900/55 p-6"><div className="flex items-start gap-3"><span className="rounded-xl bg-white/10 p-2 text-white"><ShieldCheck className="h-5 w-5" /></span><div><h2 className="text-lg font-semibold text-white">Pengelolaan data</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-white">Dashboard memproses hasil pencarian dari Kibana - ElasticSearch di server untuk kebutuhan tampilan, perhitungan, dan ekspor. Data kiriman tidak disimpan sebagai arsip pada aplikasi ini.</p></div></div></section>
  </div></DashboardLayout>;
}
