import ShipmentDetailDialog from "@/components/ShipmentDetailDialog";
import DashboardLayout from "@/components/DashboardLayout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { toast } from "sonner";
import { ClipboardList, Download, Loader2, MapPin, PackageSearch, RotateCcw, Search, Truck } from "lucide-react";
import { useMemo, useState } from "react";

function parseCodes(value: string) { return Array.from(new Set(value.split(/[\s,;]+/).map(code => code.trim().toUpperCase()).filter(Boolean))).slice(0, 100); }
function formatTime(value?: string | null) { if (!value) return "-"; const date = new Date(value); return Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat("id-ID", { dateStyle: "medium", timeStyle: "short", timeZone: "Asia/Jakarta" }).format(date); }
function downloadBase64(content: string, filename: string) { const binary = window.atob(content); const bytes = Uint8Array.from(binary, character => character.charCodeAt(0)); const url = URL.createObjectURL(new Blob([bytes], { type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" })); const link = document.createElement("a"); link.href = url; link.download = filename; link.click(); URL.revokeObjectURL(url); }

export default function Tracking() {
  const [text, setText] = useState("");
  const [submitted, setSubmitted] = useState<string[]>([]);
  const [selected, setSelected] = useState<{ connote: string; recipientName?: string; status?: string; service?: string } | null>(null);
  const codes = useMemo(() => parseCodes(text), [text]);
  const lookup = trpc.tracking.lookup.useQuery({ codes: submitted.length ? submitted : ["UNAVAILABLE"] }, { enabled: submitted.length > 0, staleTime: 30_000 });
  const exportExcel = trpc.tracking.exportExcel.useMutation({ onSuccess: result => downloadBase64(result.content, result.filename), onError: error => toast.error(error.message || "Ekspor Excel Tracking gagal dibuat.") });
  function showTracking() { const parsed = parseCodes(text); if (!parsed.length) return; setSubmitted(parsed); }
  return <DashboardLayout><div className="mx-auto w-full max-w-[1600px] space-y-6 pb-8">
    <section className="relative overflow-hidden rounded-[1.75rem] border border-white/10 bg-[#0d1426] px-6 py-7 shadow-[0_25px_80px_-45px_rgba(40,70,180,0.85)]"><div className="pointer-events-none absolute -right-20 -top-20 h-72 w-72 rounded-full bg-cyan-400/15 blur-3xl" /><div className="relative"><p className="flex items-center gap-2 text-[11px] font-semibold uppercase tracking-[0.17em] text-cyan-100"><Truck className="h-3.5 w-3.5" />Tracking workspace</p><h1 className="mt-3 text-3xl font-semibold tracking-tight text-white">Lacak beberapa kiriman sekaligus</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-white/85">Masukkan satu nomor resi per baris, atau pisahkan dengan koma. Pilih baris hasil untuk membuka data detail dan histori paket.</p></div></section>
    <section className="grid gap-5 rounded-2xl border border-white/10 bg-slate-900/55 p-5 shadow-[0_18px_48px_-38px_rgba(0,0,0,1)] backdrop-blur-xl lg:grid-cols-[1fr_auto]"><div><label className="mb-2 flex items-center gap-2 text-sm font-semibold text-white"><ClipboardList className="h-4 w-4 text-cyan-200" />Nomor resi / connote code</label><Textarea value={text} onChange={event => setText(event.target.value)} placeholder={"Contoh:\nP2607240038805\nP2607250042751"} className="min-h-36 border-white/15 bg-slate-950/70 font-mono text-sm text-white placeholder:text-white/45" /><p className="mt-2 text-xs text-white/65">{codes.length} resi siap dicari · maksimum 100 resi setiap pencarian.</p></div><div className="flex items-end gap-2"><Button onClick={showTracking} disabled={!codes.length || lookup.isFetching} className="h-10 bg-cyan-300 text-slate-950 hover:bg-cyan-200">{lookup.isFetching ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Search className="mr-2 h-4 w-4" />}Tampilkan</Button><Button onClick={() => { setText(""); setSubmitted([]); }} variant="outline" className="h-10 border-white/15 bg-white/5 text-white hover:bg-white/15 hover:text-white"><RotateCcw className="mr-2 h-4 w-4" />Reset</Button></div></section>
    {lookup.isError ? <section className="rounded-2xl border border-rose-300/20 bg-rose-500/10 p-6 text-sm text-rose-100">{lookup.error.message}</section> : submitted.length > 0 && <section className="overflow-hidden rounded-2xl border border-white/10 bg-slate-900/55 shadow-[0_18px_48px_-38px_rgba(0,0,0,1)]"><div className="flex items-center justify-between border-b border-white/10 px-5 py-4"><div><h2 className="text-sm font-semibold text-white">Hasil tracking</h2><p className="mt-1 text-xs text-white/70">Klik satu baris untuk melihat detail dan histori.</p></div><div className="flex items-center gap-2"><Button onClick={() => exportExcel.mutate({ codes: submitted })} disabled={exportExcel.isPending || !lookup.data?.some(item => item.found)} variant="outline" className="h-9 border-cyan-300/30 bg-cyan-300/10 text-xs text-cyan-50 hover:bg-cyan-300/20 hover:text-white">{exportExcel.isPending ? <Loader2 className="mr-1.5 h-3.5 w-3.5 animate-spin" /> : <Download className="mr-1.5 h-3.5 w-3.5" />}Ekspor Excel</Button><Badge className="border-0 bg-white/10 text-white">{lookup.data?.length ?? 0} resi</Badge></div></div>{lookup.isLoading ? <div className="flex items-center justify-center gap-2 p-12 text-sm text-white/75"><Loader2 className="h-4 w-4 animate-spin" />Memuat data tracking…</div> : <div className="overflow-x-auto"><table className="w-full min-w-[980px] text-left"><thead className="bg-white/[0.04] text-[10px] uppercase tracking-[0.13em] text-white/75"><tr><th className="px-5 py-3">Connote</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Produk</th><th className="px-4 py-3">Penerima</th><th className="px-4 py-3">Posisi akhir</th><th className="px-4 py-3">Pembaruan</th></tr></thead><tbody className="divide-y divide-white/10">{(lookup.data ?? []).map(item => <tr key={item.connote} onClick={() => item.found && setSelected({ connote: item.connote, recipientName: item.recipient, status: item.status, service: item.service })} className={`transition ${item.found ? "cursor-pointer hover:bg-cyan-300/10" : "opacity-60"}`}><td className="px-5 py-4 font-mono text-xs font-semibold text-cyan-100">{item.connote}</td><td className="px-4 py-4"><Badge className={`border-0 ${item.found ? "bg-cyan-300/15 text-cyan-100" : "bg-white/10 text-white/70"}`}>{item.status}</Badge></td><td className="px-4 py-4 text-sm text-white">{item.service}</td><td className="px-4 py-4 text-sm text-white">{item.recipient}</td><td className="px-4 py-4 text-sm text-white/85"><span className="flex items-center gap-1"><MapPin className="h-3.5 w-3.5 text-white/60" />{item.location}</span></td><td className="px-4 py-4 text-xs text-white/75">{formatTime(item.updatedAt)}</td></tr>)}</tbody></table></div>}</section>}
    <ShipmentDetailDialog open={Boolean(selected)} onOpenChange={open => !open && setSelected(null)} selection={selected} />
  </div></DashboardLayout>;
}
