import "leaflet/dist/leaflet.css";
import L from "leaflet";
import { MapContainer, Marker, Popup, Polyline, TileLayer, useMap, useMapEvents } from "react-leaflet";
import { useEffect, useMemo, useState } from "react";
import { routeMarkerPresentation } from "./routeMarkerPresentation";

export type RoutePoint = { connote: string; status: string; coordinate: { lat: number; lng: number }; receivedAt: string; receiver: string; podPhoto: string | null; courier: string; kind: "departure" | "delivery" | "return"; anchorSource?: "Manual" | "Pool Manual" | "Google Places"; isCod?: boolean; codAmount?: number };
type TravelMode = "motorcycle" | "walking";
const MAX_VISIBLE_MARKERS = 450;

function markerIcon(label: string, point: RoutePoint) {
  const presentation = routeMarkerPresentation(label, point.kind, point.isCod);
  const manual = point.anchorSource === "Manual" || point.anchorSource === "Pool Manual";
  const manualTitle = point.anchorSource === "Pool Manual" ? "Pool keberangkatan manual" : "Koreksi koordinat kantor manual";
  return L.divIcon({ ...presentation, className: "", html: manual ? `<span title="${manualTitle}" style="display:block;border-radius:999px;filter:drop-shadow(0 0 5px #fbbf24)">${presentation.html}</span>` : presentation.html });
}
function vehicleIcon(mode: TravelMode) { const motor = mode === "motorcycle"; return L.divIcon({ className: "", iconSize: [36, 36], iconAnchor: [18, 18], html: `<span title="${motor ? "Motor kurir bergerak" : "Kurir berjalan"}" style="display:flex;width:32px;height:32px;align-items:center;justify-content:center;border:2px solid #fff;border-radius:999px;background:#0f172a;box-shadow:0 2px 9px rgba(0,0,0,.6)"><svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="${motor ? "#67e8f9" : "#fde68a"}" stroke-width="2">${motor ? '<circle cx="5.5" cy="17.5" r="2.5"/><circle cx="18.5" cy="17.5" r="2.5"/><path d="M8 17.5h7l-2-6H9l-2 3M13 11.5l2-3h3M9 11.5 7 8.5H4"/>' : '<circle cx="12" cy="4.5" r="2"/><path d="m10 9 2 3 3-1.5M12 12l-2 4-3 2M12 12l2 5 3 2"/>'}</svg></span>` }); }
function FitRoute({ points }: { points: Array<{ lat: number; lng: number }> }) { const map = useMap(); useEffect(() => { if (points.length === 1) map.setView([points[0]!.lat, points[0]!.lng], 15); else if (points.length > 1) map.fitBounds(points.map(point => [point.lat, point.lng] as [number, number]), { padding: [36, 36] }); }, [map, points]); return null; }
function MapClickPicker({ enabled, onPick }: { enabled: boolean; onPick?: (coordinate: { lat: number; lng: number }) => void }) { useMapEvents({ click: event => { if (enabled) onPick?.({ lat: event.latlng.lat, lng: event.latlng.lng }); } }); return null; }
function AnimatedVehicle({ path, mode }: { path: Array<{ lat: number; lng: number }>; mode: TravelMode }) { const [playing, setPlaying] = useState(true); const [index, setIndex] = useState(0); useEffect(() => { setIndex(0); }, [path]); useEffect(() => { if (!playing || path.length < 2) return; const timer = window.setInterval(() => setIndex(current => current >= path.length - 1 ? 0 : current + 1), 110); return () => window.clearInterval(timer); }, [playing, path.length]); if (path.length < 2) return null; const position = path[index]!; return <><Marker position={[position.lat, position.lng]} icon={vehicleIcon(mode)} interactive={false} /><div className="absolute bottom-4 right-4 z-[500] flex gap-2"><button type="button" onClick={() => setIndex(0)} className="rounded-lg border border-amber-200/30 bg-slate-950/90 px-3 py-2 text-xs font-semibold text-amber-100 shadow-lg">Ulangi</button><button type="button" onClick={() => setPlaying(current => !current)} className="rounded-lg border border-cyan-200/30 bg-slate-950/90 px-3 py-2 text-xs font-semibold text-cyan-100 shadow-lg">{playing ? "Jeda" : "Putar"}</button></div></>; }
 function VirtualMarkers({ points, onPointSelect }: { points: RoutePoint[]; onPointSelect?: (point: RoutePoint) => void }) { const map = useMap(); const [bounds, setBounds] = useState(() => map.getBounds()); useMapEvents({ moveend: () => setBounds(map.getBounds()), zoomend: () => setBounds(map.getBounds()) }); const visible = useMemo(() => points.map((point, index) => ({ point, index })).filter(item => bounds.contains([item.point.coordinate.lat, item.point.coordinate.lng])).slice(0, MAX_VISIBLE_MARKERS), [bounds, points]); return <>{visible.map(({ point, index }) => { const deliveryNumber = points.slice(0, index + 1).filter(item => item.kind === "delivery").length; const label = point.kind === "departure" ? "A" : point.kind === "return" ? "P" : String(deliveryNumber); const title = point.kind === "departure" ? "Titik keberangkatan" : point.kind === "return" ? "Titik kepulangan" : "Titik POD"; const manual = point.anchorSource === "Manual" || point.anchorSource === "Pool Manual"; const poolManual = point.anchorSource === "Pool Manual"; return <Marker key={`${point.kind}-${point.connote}-${index}`} position={[point.coordinate.lat, point.coordinate.lng]} icon={markerIcon(label, point)} eventHandlers={{ click: () => onPointSelect?.(point) }}><Popup minWidth={245} maxWidth={270}><div className="space-y-1 text-slate-800"><p className={`text-xs font-semibold ${manual ? "text-amber-700" : point.isCod ? "text-fuchsia-700" : "text-violet-700"}`}>{title}{poolManual ? " · Pool manual" : manual ? " · Koreksi manual" : ""}</p><p className="font-mono text-sm font-bold">{point.connote}</p><p><b>Status:</b> {point.status}</p>{point.isCod && <p className="rounded bg-fuchsia-100 px-2 py-1 text-xs font-semibold text-fuchsia-900">Resi COD{point.codAmount ? ` · ${new Intl.NumberFormat("id-ID").format(point.codAmount)}` : ""}</p>}{manual && <p className="rounded bg-amber-100 px-2 py-1 text-xs text-amber-900">{poolManual ? "Koordinat ini memakai pool keberangkatan yang dipilih." : "Koordinat ini memakai koreksi manual kantor."}</p>}{point.podPhoto && <img src={point.podPhoto} alt="Foto POD" className="my-2 h-32 w-full rounded-md object-cover" />}<p><b>Informasi:</b> {point.receiver}</p><p><b>Waktu:</b> {point.receivedAt}</p><p><b>Kurir:</b> {point.courier}</p></div></Popup></Marker>; })}</>; }

export default function CourierRouteMap({ points, roadPath, travelMode = "motorcycle", deliveryInProgress = false, onPointSelect, pickingOfficeCoordinate = false, onOfficeCoordinatePick }: { points: RoutePoint[]; roadPath?: Array<{ lat: number; lng: number }>; travelMode?: TravelMode; deliveryInProgress?: boolean; onPointSelect?: (point: RoutePoint) => void; pickingOfficeCoordinate?: boolean; onOfficeCoordinatePick?: (coordinate: { lat: number; lng: number }) => void }) {
  const [picking, setPicking] = useState(pickingOfficeCoordinate);
  useEffect(() => { const toggle = (event: Event) => setPicking((event as CustomEvent<{ active?: boolean }>).detail?.active ?? true); window.addEventListener("kurir-office-coordinate-pick-start", toggle); return () => window.removeEventListener("kurir-office-coordinate-pick-start", toggle); }, []);
  if (!points.length) return <div className="flex h-[560px] items-center justify-center rounded-2xl border border-dashed border-white/15 bg-slate-950/45 px-6 text-center text-sm text-white/70">Titik koordinat POD belum tersedia untuk kurir dan filter yang dipilih.</div>;
  const path = roadPath?.length ? roadPath : points.map(point => point.coordinate); const initial = path[0]!; const hasAnchor = points.some(point => point.kind === "departure"); const manualOffice = points.some(point => point.anchorSource === "Manual" || point.anchorSource === "Pool Manual"); const poolManual = points.some(point => point.anchorSource === "Pool Manual"); const hasCod = points.some(point => point.kind === "delivery" && point.isCod);
  return <div className={`relative h-[560px] overflow-hidden rounded-2xl border bg-slate-900 ${picking ? "border-amber-300/80" : "border-white/15"}`}><div className="absolute left-3 top-3 z-[500] rounded-lg border border-white/20 bg-slate-950/90 px-3 py-2 text-[11px] text-white shadow-lg"><p className="font-semibold text-white">{hasAnchor ? deliveryInProgress ? "A: Berangkat dari kantor · P: Menunggu selesai" : "A: Berangkat dari kantor · P: Pulang ke kantor" : "Rute POD tanpa koordinat kantor terverifikasi"}</p><p className="mt-0.5 text-white/70">{poolManual ? "Penanda bercahaya emas: pool keberangkatan manual" : manualOffice ? "Penanda bercahaya emas: koreksi kantor manual" : "Marker angka: urutan POD"}{deliveryInProgress ? " · Pengantaran masih berlangsung" : " · Pengantaran selesai"}</p>{hasCod && <p className="mt-0.5 font-semibold text-fuchsia-200">Marker fuchsia: resi COD</p>}{picking && <p className="mt-1 font-semibold text-amber-200">Klik peta untuk memilih koordinat kantor</p>}</div><MapContainer center={initial} zoom={13} scrollWheelZoom className="h-full w-full"><TileLayer attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors' url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" /><FitRoute points={path} /><Polyline positions={path.map(point => [point.lat, point.lng] as [number, number])} pathOptions={{ color: "#22d3ee", weight: 4, opacity: .9 }} /><MapClickPicker enabled={picking} onPick={coordinate => { setPicking(false); onOfficeCoordinatePick?.(coordinate); window.dispatchEvent(new CustomEvent("kurir-office-coordinate-picked", { detail: coordinate })); }} /><VirtualMarkers points={points} onPointSelect={onPointSelect} /><AnimatedVehicle path={path} mode={travelMode} /></MapContainer></div>;
}
